### ISSUE TITLE
Convert hooks/024-configure-bootchart.chroot to static files

### ISSUE THREAD

**Issue by xnox** [snapcore/core20#111]
We should convert hooks/024-configure-bootchart.chroot  to simple static files in static/ folder.

There is nothing dynamic about what this hook does.

**Comment by alfonsosanchezbeato** [comment]
The hook was needed because /lib/systemd/system/systemd-bootchart.service had to be modified from the original in the deb (that one is not static). Then I thought that it was better to create the rest of the files in the hook so all the implementation was in one place and future us would not miss parts of it. But I can change to static files if you are strongly against this.

**Comment by xnox** [comment]
> because /lib/systemd/system/systemd-bootchart.service had to be modified

I would have hoped that most things were possible to do with `/usr/lib/systemd/system/systemd-bootchart.service.d/core.conf` i.e. the only thing it can't do is remove depends/wants.

**Comment by alfonsosanchezbeato** [comment]
> > because /lib/systemd/system/systemd-bootchart.service had to be modified
> 
> I would have hoped that most things were possible to do with `/usr/lib/systemd/system/systemd-bootchart.service.d/core.conf` i.e. the only thing it can't do is remove depends/wants.

I actually considered that, but it looked cleaner to me to avoid splitting the service config. No deb update is going to happen, so there would be no conflict anyway.

**Comment by alfonsosanchezbeato** [comment]
Marking won't fix for the moment, but happy to disscuss further nonetheless.
