### ISSUE TITLE
Missing mkfs.vfat, should have tests for mkfs.vfat and mkfs.ext4 existing

### ISSUE THREAD

**Issue by anonymouse64** [snapcore/core20#37]
In core20, we do not have the `mkfs.vfat` binary, but we need this because snapd in UC20 will create partitions using the gadget.yaml, so we need to ensure that the list of filesystems that snapd supports creating are supported to be created by the base snap. For now it's just ext4 and vfat AFAIK, but we could expand this list and we should make sure that we don't drop these later by adding tests here to ensure nothing is removed later.

**Comment by xnox** [comment]
/me ponders if these should be in core snaps or snapd snap.

Specifically, one has to be very careful around options that are passed to `mkfs.ext4` because new enough e2fsprogs has defaults that create generate filesystems that older kernels cannot mount. See for example the set of options that are passed to mkfs.ext4 by curtin / livecd-rootfs.

mkfs.vfat is insteresting, as one would have hoped one doesn't need to create vfat partitions - because it either pre-exists (i.e. ESP) and one doesn't need to create new ones. But I guess this is due to redundant ubuntu-boot partition that we create on RPi and choosing it to be vfat due to performance reasons.

**Comment by anonymouse64** [comment]
As discussed this morning, this should be in the core20 snap, because of the following reasons:
- it was in the core snap since forever
- @mvo5 added it to the core18 snap to get fsck back on core18
- we should keep core18/core20 in sync as much as possible with respect to fixes like this

valid use cases for dosfstools on UC20 include:
- snapd needs it to create vfat partitions on i.e. rpi4
- users may want to run fsck on their vfat partitions
